name: muz_app_updater_example
description: Example app for muz_app_updater package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  muz_app_updater:
    path: ../
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 