name: muz_app_updater
description: A Flutter package for app update management with Firebase Firestore integration.
version: 0.0.4
homepage: https://github.com/muzzammil763/muz_app_updater

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  package_info_plus: ^4.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

