name: muz_app_updater
description: A Flutter package for app update management with Firebase Firestore integration.
version: 0.0.6
homepage: https://github.com/muzzammil763/muz_app_updater

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  package_info_plus: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

